###
### https://www.appveyor.com/docs/appveyor-yml/
###

version: 0.0.{build}
init:
- cmd: git config --global core.autocrlf true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
notifications:
- provider: Email
  to:
  - keith+build@sol3.net
  subject: CI build 0.0.{build} failed!
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
clone_folder: C:\sol3
environment:
  build: '{build}'
  matrix:
  - project_name: \src\Standard\Sol3.Standard.Infrastructure
  - project_name: \src\Core\Sol3.Core.Infrastructure
  - project_name: \src\Framework\Sol3.Framework.Infrastructure
nuget:
  account_feed: true
  project_feed: true
build_script:
- pwsh: >-
    Set-Location .\$env:project_name

    ./build.ps1

    Set-Location \
artifacts:
- path: '*/.nupkg'
deploy: off