version: 0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
clone_folder: C:\sol3
environment:
  build: '{build}'
  matrix:
  - project_name: Sol3.Standard.Infrastructure
    dir_name: '\src\Standard\'
  - project_name: Sol3.Core.Infrastructure
    dir_name: '\src\Core\'
  - project_name: Sol3.Framework.Infrastructure
    dir_name: '\src\Framework\'
nuget:
  account_feed: true
  project_feed: true
build_script:
- pwsh: >-
    Set-Location .\$env:dir_name\$env:project_name

    ./build.ps1

    Set-Location \
deploy: off
notifications:
- provider: Email
  to:
  - keith+build@sol3.net
  subject: Appveyor CI build 0.0.{build} (event)!
  message: Results are at https://ci.appveyor.com/project/KeithBarrows/sol3
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: true
- provider: Email
  to:
  - keith+build@sol3.net
  subject: Appveyor CI build 0.0.{build} failed!
  message: Results are at https://ci.appveyor.com/project/KeithBarrows/sol3
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false