version: '0.0.{build}'
image: Visual Studio 2017
configuration: Release

init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore Sol3.Infrastructure/Sol3.Infrastructure.csproj --verbosity m

build_script:
  - cmd: dotnet build Sol3.Infrastructure/Sol3.Infrastructure.csproj
  - cmd: dotnet pack  -c Release /p:PackageVersion=0.0.{build} 

notifications:
- provider: Email
  to:
  - keith@sol3.net
  subject: Latest CI build failed!
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

artifacts:

deploy:
  provider: NuGet
  server: https://keithbarrows.pkgs.visualstudio.com/_packaging/packages/nuget/v3/index.json
  api_key:
    secure: og20mPRme2B1liUL1znQvg==
  skip_symbols: true

after_build:
  # For once the build has completed
 
on_finish :
  # any cleanup in here
deploy: off