version: '0.0.{build}'
image: Visual Studio 2017
configuration: Release

notifications:
- provider: Email
  to:
  - keith@sol3.net
  subject: CI build 0.0.{build} failed!
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false


init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true

before_build:
- pwsh: >-
    dotnet --version
    dotnet restore Sol3.Infrastructure/Sol3.Infrastructure.csproj --verbosity m

build:
  project: Sol3.Infrastructure/Sol3.Infrastructure.csproj
  verbosity: normal

before_package:
- pwsh: dotnet --version  # place holder

after_build:
- pwsh: >-
    dotnet --version  # place holder
    # pack this one nuget
    # publish nuget to VSTS